apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231123091221.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231123091221.0.0+build.02e9424
  releaseNotes: |
    Release v20231123091221.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-23-11-2023-00-48-52-693624192/where-for-dinner-search-my-apps-bundle@sha256:41cec526d635f453f06f815e909cd0126a0290231b01037db91abd70c08b290c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

