apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20231123091321.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20231123091321.0.0+build.02e9424
  releaseNotes: |
    Release v20231123091321.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-23-11-2023-00-48-52-693624192/where-for-dinner-ui-my-apps-bundle@sha256:20065f9849b73e10946eb15f25d0060a525b0c8be0a3a6a8ad10a5e9940f0358
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

