apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20231123091154.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20231123091154.0.0+build.02e9424
  releaseNotes: |
    Release v20231123091154.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-23-11-2023-00-48-52-693624192/where-for-dinner-availability-my-apps-bundle@sha256:1b84931f40546e28a3f6259eff6acac4362bac7b1a19eee15aba7b2ed6e3775d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

